# Generated by Django 4.1 on 2023-01-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoeuser',
            name='phone_number',
        ),
    ]
