# Generated by Django 4.1 on 2022-09-19 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_size', models.CharField(choices=[('first_small', '3'), ('second_small', '4'), ('first_medium', '5'), ('second_medium', '6'), ('first_large', '7'), ('second_large', '8')], default='first_small', max_length=50)),
                ('shoe_type', models.CharField(choices=[('FLATS', 'flat'), ('BOOTS', 'boot'), ('TRAINERS', 'trainers'), ('SANDLES', 'sandals')], default='FLATS', max_length=50)),
                ('order_status', models.CharField(choices=[('PENDING', 'pending'), ('IN_TRANSIT', 'in_transit'), ('DELIVERED', 'delivered')], default='PENDING', max_length=50)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
