# Generated by Django 4.1 on 2023-01-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_status_alter_order_shoe_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shoe_size',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='3', max_length=50),
        ),
    ]
