# Generated by Django 4.1 on 2023-01-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_shoe_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shoe_size',
            field=models.CharField(choices=[('small', 'SMALL'), ('medium', 'MEDIUM'), ('large', 'LARGE')], default='small', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='shoe_type',
            field=models.CharField(choices=[('flats', 'FLATS'), ('boots', 'BOOTS'), ('trainers', 'TRAINERS'), ('sandals', 'SANDLES')], default='flats', max_length=50),
        ),
    ]
